### ISSUE TITLE
Package conflicting with itself

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/geopandas-feedstock#1]
Same as https://github.com/conda-forge/rtree-feedstock/issues/1

```
BUILD END: geopandas-0.1.1-py34_0
TEST START: geopandas-0.1.1-py34_0
Fetching package metadata: ........ 
Solving package specifications: .... 
Error: The following specifications were found to be in conflict:
  - geopandas 0.1.1 py34_0 -> python 3.4*
  - python 3.4*
Use "conda info <package>" to see the dependencies for each package. 
```

**Comment by pelson** [comment]
That's an odd one. Nothing obvious in the recipe...

**Comment by ocefpaf** [comment]
I am trying to re-build the c-libs with features enabled to see if it has any relation. Note that `HDF5` problem is similar. (See https://github.com/conda-forge/hdf5-feedstock/issues/1#issue-143525048)

**Comment by ocefpaf** [comment]
Seems to be resolved with the latest updates.
