### ISSUE TITLE
Package for python 3.4 missing?

### ISSUE THREAD

**Issue by jorisvandenbossche** [conda-forge/geopandas-feedstock#2]
```
[geopandas_test_py3] C:\Users\vdbosscj>conda install -c conda-forge geopandas
Fetching package metadata: ......
Solving package specifications: ............................
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|##################################################| 100%

Hint: the following packages conflict with each other:
  - geopandas
  - python 3.4*

Use 'conda info geopandas' etc. to see the dependencies for each package.

Note that the following features are enabled:
  - vc10
```

And indeed, the file is not here: https://anaconda.org/conda-forge/geopandas/files

**Comment by jorisvandenbossche** [comment]
And the build status indication of appveyor is also failing because of this: https://ci.appveyor.com/project/conda-forge/geopandas-feedstock/branch/master

The build log ends with

```
BUILD END: geopandas-0.1.1-py34_0
TEST START: geopandas-0.1.1-py34_0
Fetching package metadata: ........ 
Solving package specifications: .... 
Error: The following specifications were found to be in conflict:
  - geopandas 0.1.1 py34_0 -> rtree
Use "conda info <package>" to see the dependencies for each package. 
Command exited with code 1
```

**Comment by ocefpaf** [comment]
I am re-building `geos` and `gdal` enabling features hoping that problem will go away. I will ping you back once this is done.

**Comment by jorisvandenbossche** [comment]
`rtree` seems to have 3.4 missing as well, but I can't really make sense of the log file over there: https://ci.appveyor.com/project/conda-forge/rtree-feedstock/branch/master/job/q09jprd044pdam73 (it cannot find itself?)

**Comment by ocefpaf** [comment]
> cannot find itself?

Neither can we :smile: (But we are on it https://github.com/conda-forge/rtree-feedstock/issues/1)

**Comment by ocefpaf** [comment]
They should be in the channel now: http://anaconda.org/conda-forge/geopandas/files

**Comment by jorisvandenbossche** [comment]
And tested it by installing geopandas in a clean py3.4 env on Windows, everything ok. Thanks!

**Comment by pelson** [comment]
@jorisvandenbossche - it would be super to have you on the maintainers list. Interested in submitting a PR? Similarly, are you interested @kjordahl?

Maintenance is pretty much a case up [updating the version](https://github.com/conda-forge/geopandas-feedstock/blob/master/recipe/meta.yaml#L1) when a new tag is added, and merging [automated maintenance PRs](https://github.com/conda-forge/geopandas-feedstock/pull/3) which keep the continuous integration in line with the other ~250 conda-forge feedstocks.

**Comment by jorisvandenbossche** [comment]
@pelson Will do!
