### ISSUE TITLE
Coninuum Anaconda - trial lisence expires in 30 days - isn't it free?

### ISSUE THREAD

**Issue by scienceyogi** [conda-forge/geopandas-feedstock#26]
Hello all, 

I've had to install anaconda and the GDAL library MANY times this month (long story) on different computers. Needless to say, I had it down to an art. Starting 3 days ago, I got the following when using "conda install ____" (I get it for any library) OR even just starting an application (e.g., ipython):

Vendor:  continuum
Product: anaconda
Message: trial mode expires in 30 days

I tried looking this up, but everyone is talking about the mkl library and nothing about anaconda causing this problem. 

Also, I suspect that this error is why both my (and my friend who has a slightly different) fool-proof method for installing gdal has ceased working.

ANY Help would be greatly appreciated!

**Comment by jorisvandenbossche** [comment]
This indicates that you somehow install numpy with mkl feature, which is independent from gdal or geopandas. 
I would try and see if `conda remove mkl` works, and if you have more problems / questions with this, https://github.com/ContinuumIO/anaconda-issues/issues is a more appropriate place.

**Comment by jorisvandenbossche** [comment]
Closing this as it is not related with `geopandas`. If you have problems with installing `gdal` from conda-forge, you can open an issue at https://github.com/conda-forge/gdal-feedstock. But if it is with the `gdal` from Anaconda itself, again https://github.com/ContinuumIO/anaconda-issues/issues is the better place to ask.

**Comment by antoinedumontneira** [comment]
I tried everything. The only solution that worked for me was conda update --all
