### ISSUE TITLE
Development build of geopandas-cython branch

### ISSUE THREAD

**Issue by mrocklin** [conda-forge/geopandas-feedstock#29]
Geopandas has an experimental branch with Cython support.  We would like to make it easy for people to try this build, hopefully by publishing conda packages.  Is it reasonable to use conda-forge to produce dev or experimental builds of a package?

**Comment by ocefpaf** [comment]
It is and I have a particular interest in that. I'll try to get a recipe for it later today.

**Comment by ocefpaf** [comment]
Donein #30
