### ISSUE TITLE
Issue with import geopandas as gpd

### ISSUE THREAD

**Issue by lourew** [conda-forge/geopandas-feedstock#42]
Hey any help would be much appreciated !

Issue:

Trying to import geopandas into Spyder anaconda

In spyder typed in; 

`import geopandas as gpd`

output was; 

```
Traceback (most recent call last):

  File "<ipython-input-1-a62d01c1d62e>", line 1, in <module>
    import geopandas as gpd

  File "/Users/name/anaconda3/lib/python3.5/site-packages/geopandas/__init__.py", line 4, in <module>
    from geopandas.io.file import read_file

  File "/Users/name/anaconda3/lib/python3.5/site-packages/geopandas/io/file.py", line 3, in <module>
    import fiona

  File "/Users/name/anaconda3/lib/python3.5/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path

  File "/Users/name/anaconda3/lib/python3.5/site-packages/fiona/collection.py", line 7, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator

ImportError: dlopen(/Users/name/anaconda3/lib/python3.5/site-packages/fiona/ogrext.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libnetcdf.11.dylib
  Referenced from: /Users/name/anaconda3/lib/libgdal.20.dylib
  Reason: Incompatible library version: libgdal.20.dylib requires version 12.0.0 or later, but libnetcdf.11.dylib provides version 11.0.0
```

In mac terminal typed in; 

` conda config --add channels conda-forge`

then;

`conda install geopandas`

output was; 
```
Solving environment: done

 Package Plan 

  environment location: /Users/name/anaconda3

  added / updated specs: 
    - geopandas


The following packages will be UPDATED:

    ca-certificates: 2018.03.07-0      --> 2018.4.16-0      conda-forge
    certifi:         2018.4.16-py35_0  --> 2018.4.16-py35_0 conda-forge
    conda:           4.5.8-py35_0      --> 4.5.8-py35_1     conda-forge
    openssl:         1.0.2o-h26aff7b_0 --> 1.0.2o-0         conda-forge

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

$ conda list

```
Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py35h0f4cdc0_0  
alabaster                 0.7.11                   py35_0  
anaconda-client           1.6.14                   py35_0  
anaconda-navigator        1.8.7                    py35_0  
anaconda-project          0.8.2            py35ha24014a_0  
appnope                   0.1.0            py35hd172556_0  
appscript                 1.0.1            py35hdfff33c_1  
asn1crypto                0.24.0                   py35_0  
astroid                   1.6.5                    py35_0  
astropy                   3.0.3            py35h1de35cc_2  
atomicwrites              1.1.5                    py35_0  
attrs                     18.1.0                   py35_0  
babel                     2.6.0                    py35_0  
backcall                  0.1.0                    py35_0  
backports                 1.0              py35h2556c16_1  
backports.shutil_get_terminal_size 1.0.0            py35h40fcb1f_2  
beautifulsoup4            4.6.0            py35hb75f182_1  
bitarray                  0.8.2            py35h1de35cc_0  
bkcharts                  0.2              py35h18a45e2_0  
blas                      1.0                         mkl  
blaze                     0.11.3           py35h385aa17_0  
bleach                    2.1.3                    py35_0  
blosc                     1.14.3               hd9629dc_0  
bokeh                     0.13.0                   py35_0  
boto                      2.48.0           py35h10f7326_1  
bottleneck                1.2.1            py35h969083f_0  
bzip2                     1.0.6                h1de35cc_5  
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py35_0    conda-forge
cffi                      1.11.5           py35h342bebf_0  
chardet                   3.0.4            py35h16a84c2_1  
click                     6.7              py35hcc65ea6_0  
click-plugins             1.0.3            py35hcd8d381_0  
cligj                     0.4.0            py35h225cd6b_0  
cloudpickle               0.5.3                    py35_0  
clyent                    1.2.2            py35h63ae3d7_0  
colorama                  0.3.9            py35h1d66b2b_0  
conda                     4.5.8                    py35_1    conda-forge
conda-build               3.10.9                   py35_0  
conda-env                 2.6.0                h36134e3_0  
conda-verify              2.0.0            py35h2ddbee6_0  
contextlib2               0.5.5            py35hc2c67b4_0  
cryptography              2.2.2            py35h1de35cc_0  
curl                      7.60.0               ha441bb4_0  
cycler                    0.10.0           py35hb89929e_0  
cython                    0.28.3           py35h1de35cc_0  
cytoolz                   0.9.0.1          py35h1de35cc_0  
dask                      0.18.1                   py35_0  
dask-core                 0.18.1                   py35_0  
datashape                 0.5.4            py35hd065018_0  
dbus                      1.13.2               h760590f_1  
decorator                 4.3.0                    py35_0  
descartes                 1.0.2                    py35_0    ioos
distributed               1.22.0                   py35_0  
docutils                  0.14             py35hb13dbd9_0  
entrypoints               0.2.3            py35h837ec6f_2  
et_xmlfile                1.0.1            py35h40eb147_0  
expat                     2.2.5                hb8e80ba_0  
fastcache                 1.0.2            py35h1de35cc_2  
filelock                  3.0.4                    py35_0  
fiona                     1.7.0               np111py35_0    ioos
flask                     1.0.2                    py35_1  
flask-cors                3.0.6                    py35_0  
folium                    0.2.1                    py35_0    ioos
freetype                  2.8                  h12048fb_1  
gdal                      2.1.0                    py35_0  
geojson                   1.3.3                    py35_0    ioos
geopandas                 0.4.0                      py_0    conda-forge
geopy                     1.10.0                   py35_0    ioos
geos                      3.5.0                         0  
geotiff                   1.4.1                         0  
get_terminal_size         1.0.0                h7520d66_0  
gettext                   0.19.8.1             h15daf44_3  
gevent                    1.3.4            py35h1de35cc_0  
glib                      2.56.1               h35bc53a_0  
glob2                     0.6              py35hdef87b6_0  
gmp                       6.1.2                hb37e062_1  
gmpy2                     2.0.8            py35h212fb8a_2  
greenlet                  0.4.13           py35h1de35cc_0  
h5py                      2.7.0               np111py35_0  
hdf4                      4.2.12                        1  
hdf5                      1.8.17                        0    ioos
heapdict                  1.0.0                    py35_2  
html5lib                  1.0.1            py35h2f9c1c0_0  
icu                       58.2                 h4b95b61_1  
idna                      2.7                      py35_0  
imageio                   2.3.0                    py35_0  
imagesize                 1.0.0                    py35_0  
intel-openmp              2018.0.0                      8  
ipykernel                 4.8.2                    py35_0  
ipython                   6.4.0                    py35_0  
ipython_genutils          0.2.0            py35hf129286_0  
ipywidgets                7.2.1                    py35_0  
isort                     4.3.4                    py35_0  
itsdangerous              0.24             py35hfbd69cd_1  
jbig                      2.1                  h4d881f8_0  
jdcal                     1.4                      py35_0  
jedi                      0.12.0                   py35_1  
jinja2                    2.10             py35h6ff70ae_0  
jpeg                      9b                   he5867d9_2  
jsonschema                2.6.0            py35h2dd9e4b_0  
jupyter                   1.0.0                    py35_4  
jupyter_client            5.2.3                    py35_0  
jupyter_console           5.2.0            py35hd2aa692_1  
jupyter_core              4.4.0            py35h4ad9194_0  
jupyterlab                0.32.1                   py35_0  
jupyterlab_launcher       0.10.5                   py35_0  
kealib                    1.4.6                         0    ioos
kiwisolver                1.0.1            py35h219a9d8_0  
lazy-object-proxy         1.3.1            py35h7293e74_0  
libcurl                   7.60.0               hf30b1f0_0  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1.20170329         hb402a30_2  
libffi                    3.2.1                h475c297_4  
libgdal                   2.1.0                         0  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libnetcdf                 4.4.1                         0    ioos
libpng                    1.6.34               he12f830_0  
libpq                     10.3                 hf30b1f0_0  
libsodium                 1.0.16               h3efe00b_0  
libspatialindex           1.8.5                         0    ioos
libssh2                   1.8.0                h322a93b_4  
libtiff                   4.0.9                hcb84e12_1  
libxml2                   2.9.8                hab757c2_1  
libxslt                   1.1.32               hb819dd2_0  
llvmlite                  0.23.2           py35hc454e04_0  
locket                    0.2.0            py35h58cf053_1  
lxml                      3.6.4                    py35_0    ioos
lzo                       2.10                 h362108e_2  
markupsafe                1.0              py35h9ba0a7f_1  
matplotlib                2.2.2            py35ha7267d0_0  
mccabe                    0.6.1            py35h3f6a9a1_0  
mistune                   0.8.3            py35h1de35cc_1  
mkl                       2018.0.2                      1  
mkl-service               1.1.2            py35h6a6947a_4  
mkl_fft                   1.0.1            py35h917ab60_0  
mkl_random                1.0.1            py35h78cc56f_0  
more-itertools            4.2.0                    py35_0  
mpc                       1.0.3                h7a72875_5  
mpfr                      3.1.5                h711e7fd_2  
mplleaflet                0.0.5                    py35_0    ioos
mpmath                    1.0.0            py35he743aed_2  
msgpack                   0.5.6                     <pip>
msgpack-python            0.5.6            py35h04f5b5a_0  
multipledispatch          0.5.0                    py35_0  
munch                     2.3.2                    py35_0  
navigator-updater         0.2.1                    py35_0  
nbconvert                 5.3.1            py35h63fb950_0  
nbformat                  4.4.0            py35h41c2038_0  
ncurses                   6.1                  h0a44026_0  
networkx                  2.1                      py35_0  
nltk                      3.3.0                    py35_0  
nose                      1.3.7            py35h9ce1e3a_2  
notebook                  5.5.0                    py35_0  
numba                     0.38.1           py35h6440ff4_0  
numexpr                   2.6.5            py35h057f876_0  
numpy                     1.11.3           py35h8a80b8c_4  
numpy-base                1.14.3           py35ha9ae307_2  
numpydoc                  0.8.0                    py35_0  
odo                       0.5.1            py35h7f7a387_0  
olefile                   0.45.1                   py35_0  
openpyxl                  2.5.4                    py35_0  
openssl                   1.0.2o                        0    conda-forge
packaging                 17.1                     py35_0  
pandas                    0.22.0           py35h0a44026_0  
pandoc                    1.19.2.1             ha5e8f32_1  
pandocfilters             1.4.2            py35hff87490_1  
parso                     0.2.1                    py35_0  
partd                     0.3.8            py35h6fadee7_0  
path.py                   11.0.1                   py35_0  
pathlib2                  2.3.2                    py35_0  
patsy                     0.5.0                    py35_0  
pcre                      8.42                 h378b8a2_0  
pep8                      1.7.1                    py35_0  
pexpect                   4.6.0                    py35_0  
pickleshare               0.7.4            py35h9517181_0  
pillow                    5.1.0            py35hfcce615_0  
pip                       10.0.1                   py35_0  
pkginfo                   1.4.2                    py35_1  
pluggy                    0.6.0            py35hf57b818_0  
ply                       3.11                     py35_0  
proj4                     4.9.2                         0  
prompt_toolkit            1.0.15           py35h93950c5_0  
psutil                    5.4.6            py35h1de35cc_0  
psycopg2                  2.7.5            py35hdbc3d79_0  
ptyprocess                0.6.0                    py35_0  
py                        1.5.4                    py35_0  
pycodestyle               2.4.0                    py35_0  
pycosat                   0.6.3            py35h745f8c1_0  
pycparser                 2.18             py35hab820b0_1  
pycrypto                  2.6.1            py35h1de35cc_8  
pycurl                    7.43.0.2         py35hdbc3d79_0  
pyflakes                  2.0.0                    py35_0  
pygments                  2.2.0            py35h392a662_0  
pylint                    1.9.2                    py35_0  
pyodbc                    4.0.23           py35h0a44026_0  
pyopenssl                 18.0.0                   py35_0  
pyparsing                 2.2.0            py35h31fab04_0  
pyproj                    1.9.5.1                  py35_0  
pyqt                      5.9.2            py35h11d3b92_0  
pysal                     1.12.0                   py35_0    ioos
pysocks                   1.6.8                    py35_0  
pytables                  3.3.0               np111py35_0  
pytest                    3.6.2                    py35_0  
pytest-arraydiff          0.2                      py35_0  
pytest-astropy            0.4.0                    py35_0  
pytest-doctestplus        0.1.3                    py35_0  
pytest-openfiles          0.3.0                    py35_0  
pytest-remotedata         0.3.0                    py35_0  
python                    3.5.5                h0a44026_3  
python-dateutil           2.7.3                    py35_0  
python.app                2                py35he4d1c94_7  
pytz                      2018.5                   py35_0  
pywavelets                0.5.2            py35h9dc8fb8_0  
pyyaml                    3.12             py35hf8cec8a_1  
pyzmq                     17.0.0           py35h1de35cc_1  
qt                        5.9.5                h02808f3_0  
qtawesome                 0.4.4            py35h21e61ad_0  
qtconsole                 4.3.1            py35hd6d667b_0  
qtpy                      1.4.2                    py35_0  
readline                  7.0                  hc1231fa_4  
requests                  2.19.1                   py35_0  
rope                      0.10.7           py35h27868a4_0  
rtree                     0.8.2                    py35_0    ioos
ruamel_yaml               0.15.42          py35h1de35cc_0  
scikit-image              0.14.0           py35h0a44026_1  
scikit-learn              0.19.1           py35h2b554eb_0  
scipy                     1.1.0            py35hcaad992_0  
seaborn                   0.8.1            py35he0bbe96_0  
send2trash                1.5.0                    py35_0  
setuptools                39.2.0                   py35_0  
shapely                   1.5.16                   py35_0  
simplegeneric             0.8.1                    py35_2  
singledispatch            3.4.0.3          py35h0acf360_0  
sip                       4.19.8           py35h0a44026_0  
six                       1.11.0           py35h39a4c60_1  
snappy                    1.1.7                he62c110_3  
snowballstemmer           1.2.1            py35hbb7be01_0  
sortedcollections         1.0.1                    py35_0  
sortedcontainers          2.0.4                    py35_0  
sphinx                    1.7.5                    py35_0  
sphinxcontrib             1.0              py35h3eabf46_1  
sphinxcontrib-websupport  1.1.0                    py35_1  
spyder                    3.2.8                    py35_0  
sqlalchemy                1.2.8            py35h1de35cc_0  
sqlite                    3.23.1               hf1716c9_0  
statsmodels               0.9.0            py35h917ab60_0  
sympy                     1.1.1            py35he478fab_0  
tblib                     1.3.2            py35h1b9c5fd_0  
terminado                 0.8.1                    py35_1  
testpath                  0.3.1            py35hf8009f4_0  
tk                        8.6.7                h35a86e2_3  
toolz                     0.9.0                    py35_0  
tornado                   5.0.2                    py35_0  
traitlets                 4.3.2            py35hd3d1486_0  
typing                    3.6.4                    py35_0  
unicodecsv                0.14.1           py35h2154ad0_0  
unixodbc                  2.3.6                h3efe00b_0  
urllib3                   1.23                     py35_0  
wcwidth                   0.1.7            py35hdd0c235_0  
webencodings              0.5.1            py35hcf8ebf9_1  
werkzeug                  0.14.1                   py35_0  
wheel                     0.31.1                   py35_0  
widgetsnbextension        3.2.1                    py35_0  
wrapt                     1.10.11          py35ha18cf31_0  
xerces-c                  3.1.4                         0    ioos
xlrd                      1.1.0            py35h892fcf7_1  
xlsxwriter                1.0.5                    py35_0  
xlwings                   0.11.8                   py35_0  
xlwt                      1.2.0            py35hf70d7fa_0  
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
zeromq                    4.2.5                h378b8a2_0  
zict                      0.1.3            py35h1ae85d2_0  
zlib                      1.2.11               hf3cbc9b_2 
```

$ conda info

```
active environment : None
       user config file : /Users/name/.condarc
 populated config files : /Users/name/.condarc
          conda version : 4.5.8
    conda-build version : 3.10.9
         python version : 3.5.5.final.0
       base environment : /Users/name/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/name/anaconda3/pkgs
                          /Users/name/.conda/pkgs
       envs directories : /Users/name/anaconda3/envs
                          /Users/name/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.8 requests/2.19.1 CPython/3.5.5 Darwin/17.5.0 OSX/10.13.4
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by jdmcbr** [comment]
You have a mix of packages from conda-forge and the defaults channel. Try creating a clean environment and installing `geopandas` within that environment (see docs on creating an environment [here](https://conda.io/docs/user-guide/tasks/manage-python.html)).

**Comment by ocefpaf** [comment]
You also have the extremely old and deprecated `ioos` channel! Please do not use that one b/c we moved everything over to conda-forge 3 years ago!!

**Comment by ocefpaf** [comment]
Please see the docs that @jdmcbr recommend above and https://conda-forge.org/docs/conda-forge_gotchas.html

**Comment by lourew** [comment]
Hi,

I have created a new environment with;

`conda create myenv2`
`activate myenv2`

Then tried geopandas again

`conda install -c conda-forge geopandas`

In spyder i have run;

`import geopandas as pd`

The output is;
`Traceback (most recent call last):

  File "<ipython-input-1-a62d01c1d62e>", line 1, in <module>
    import geopandas as gpd

  File "C:\Users\lrewrie\AppData\Local\Continuum\anaconda3\envs\myenv2\lib\site-packages\geopandas\__init__.py", line 4, in <module>
    from geopandas.io.file import read_file

  File "C:\Users\lrewrie\AppData\Local\Continuum\anaconda3\envs\myenv2\lib\site-packages\geopandas\io\file.py", line 3, in <module>
    import fiona

  File "C:\Users\lrewrie\AppData\Local\Continuum\anaconda3\envs\myenv2\lib\site-packages\fiona\__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path

  File "C:\Users\lrewrie\AppData\Local\Continuum\anaconda3\envs\myenv2\lib\site-packages\fiona\collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator

ImportError: DLL load failed: The specified module could not be found.`

$ conda list

`myenv2) C:\Users\lrewrie>conda list
# packages in environment at C:\Users\lrewrie\AppData\Local\Continuum\anaconda3\envs\myenv2:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.11                     py_3    conda-forge
asn1crypto                0.24.0                     py_1    conda-forge
astroid                   1.6.5                    py36_0    conda-forge
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    2.1.3                      py_0    conda-forge
bzip2                     1.0.6                hfa6e2cd_2    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.11.5           py36hfa6e2cd_1    conda-forge
chardet                   3.0.4                    py36_3    conda-forge
click                     6.7                        py_1    conda-forge
click-plugins             1.0.3                      py_1    conda-forge
cligj                     0.4.0                    py36_0    conda-forge
cloudpickle               0.5.3                      py_0    conda-forge
colorama                  0.3.9                      py_1    conda-forge
cryptography              2.3              py36h74b6da3_0    conda-forge
cryptography-vectors      2.3                      py36_1    conda-forge
curl                      7.61.0               h7602738_0
cycler                    0.10.0                     py_1    conda-forge
decorator                 4.3.0                      py_0    conda-forge
descartes                 1.1.0                      py_2    conda-forge
docutils                  0.14                     py36_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
expat                     2.2.5                he025d50_1    conda-forge
fiona                     1.7.13           py36h2fc6367_3    conda-forge
freetype                  2.8.1                ha63716d_1    conda-forge
freexl                    1.0.5                hd288d7e_1    conda-forge
gdal                      2.2.4            py36h2fc6367_1    conda-forge
geopandas                 0.4.0                      py_0    conda-forge
geos                      3.6.2                he025d50_2    conda-forge
geotiff                   1.4.2                h2080a26_2    conda-forge
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.2               hbc3b0e7_1    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                 ha66f8fd_1
idna                      2.7                      py36_2    conda-forge
imagesize                 1.0.0                      py_1    conda-forge
intel-openmp              2018.0.3                      0
ipykernel                 4.8.2                    py36_0    conda-forge
ipython                   6.5.0                    py36_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     4.3.4                    py36_0    conda-forge
jedi                      0.12.1                   py36_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                   hfa6e2cd_0    conda-forge
jsonschema                2.6.0                    py36_1    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kealib                    1.4.9                h4380d0d_2    conda-forge
keyring                   13.2.1                   py36_0    conda-forge
kiwisolver                1.0.1                    py36_1    conda-forge
lazy-object-proxy         1.3.1            py36hfa6e2cd_0    conda-forge
libcurl                   7.61.0               h7602738_0
libgdal                   2.2.4                hf00ed0c_6    conda-forge
libiconv                  1.15                 hfa6e2cd_1    conda-forge
libnetcdf                 4.6.1                ha2173a7_4    conda-forge
libpng                    1.6.34               h7602738_1    conda-forge
libpq                     9.6.6                h14f23c8_0
libspatialindex           1.8.5                he025d50_2    conda-forge
libspatialite             4.3.0a              h582a839_21    conda-forge
libssh2                   1.8.0                hc4dcbb0_2    conda-forge
libtiff                   4.0.9                hf1753bf_1    conda-forge
libxml2                   2.9.8                haffccfe_2    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.2.2                    py36_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.3            py36hfa6e2cd_2    conda-forge
mkl                       2018.0.3                      1
mkl_fft                   1.0.5                    py36_0    conda-forge
mkl_random                1.0.1                    py36_0    conda-forge
munch                     2.3.2                      py_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
numpy                     1.14.3           py36h9fa60d3_2
numpy-base                1.14.3           py36h5c71026_0
numpydoc                  0.8.0                      py_1    conda-forge
openjpeg                  2.3.0                h25a6d84_3    conda-forge
openssl                   1.0.2o               hfa6e2cd_1    conda-forge
packaging                 17.1                       py_0    conda-forge
pandas                    0.23.4           py36h830ac7b_0    conda-forge
pandoc                    2.2.2                hde52d81_1    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.3.1                      py_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pip                       18.0                     py36_1    conda-forge
proj4                     4.9.3                hcf24537_7
prompt_toolkit            1.0.15                   py36_0    conda-forge
psutil                    5.4.6                    py36_0    conda-forge
psycopg2                  2.7.5            py36h74b6da3_1    conda-forge
pycodestyle               2.4.0                      py_1    conda-forge
pycparser                 2.18                       py_1    conda-forge
pyflakes                  2.0.0                      py_0    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pylint                    1.9.2                    py36_0    conda-forge
pyopenssl                 18.0.0                   py36_0    conda-forge
pyparsing                 2.2.0                      py_1    conda-forge
pyproj                    1.9.5.1                  py36_0    conda-forge
pyqt                      5.6.0            py36h764d66f_6    conda-forge
pysal                     1.14.4.post2             py36_0    conda-forge
pysocks                   1.6.8                    py36_1    conda-forge
python                    3.6.6                he025d50_0    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.5                     py_0    conda-forge
pywin32-ctypes            0.1.2                    py36_0    conda-forge
pyzmq                     17.0.0                   py36_3    conda-forge
qt                        5.6.2                h2639256_8    conda-forge
qtawesome                 0.4.4              pyh8a2030e_1    conda-forge
qtconsole                 4.3.1                    py36_0    conda-forge
qtpy                      1.4.2              pyh8a2030e_1    conda-forge
requests                  2.19.1                   py36_1    conda-forge
rope                      0.10.7                     py_1    conda-forge
rtree                     0.8.3                    py36_0    conda-forge
scipy                     1.1.0            py36h672f292_0
setuptools                40.0.0                   py36_1    conda-forge
shapely                   1.6.4            py36hc90234e_1    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
sphinx                    1.7.5                    py36_0    conda-forge
sphinxcontrib-websupport  1.1.0                    py36_0    conda-forge
spyder                    3.3.0                    py36_2    conda-forge
spyder-kernels            0.2.4                      py_2    conda-forge
sqlalchemy                1.2.10           py36hfa6e2cd_1    conda-forge
sqlite                    3.24.0               hb652765_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
tornado                   5.1              py36hfa6e2cd_1    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
urllib3                   1.23                     py36_1    conda-forge
vc                        14.1                 h0510ff6_3
vs2015_runtime            15.5.2                        3
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                    py36_0    conda-forge
wheel                     0.31.1                   py36_1    conda-forge
win_inet_pton             1.0.1                    py36_1    conda-forge
wincertstore              0.2                      py36_2    conda-forge
wrapt                     1.10.11                  py36_0    conda-forge
xerces-c                  3.2.0                h44c76bb_2
xz                        5.2.4                h2fa13f4_1    conda-forge
zlib                      1.2.11               h2fa13f4_3    conda-forge

(myenv2) C:\Users\lrewrie>`

$ conda info

`     active environment : myenv2
    active env location : C:\Users\lrewrie\AppData\Local\Continuum\anaconda3\envs\myenv2
            shell level : 2
       user config file : C:\Users\lrewrie\.condarc
 populated config files : C:\Users\lrewrie\.condarc
          conda version : 4.5.9
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : C:\Users\lrewrie\AppData\Local\Continuum\anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\lrewrie\AppData\Local\Continuum\anaconda3\pkgs
                          C:\Users\lrewrie\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\lrewrie\AppData\Local\Continuum\anaconda3\envs
                          C:\Users\lrewrie\AppData\Local\conda\conda\envs
                          C:\Users\lrewrie\.conda\envs
               platform : win-64
             user-agent : conda/4.5.9 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.15063
          administrator : False
             netrc file : None
           offline mode : False`

I have looked through forums for the past few hours and I cant figure out how to import geopandas.

Any help would be much appreciated as I really need to map :/.

Thanks!!!!

**Comment by ocefpaf** [comment]
All the packages that do not have a `conda-forge` in your list are coming from `defaults` and that is an issue that may be avoided by followed the instructions in:

https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels

and more recently:

https://github.com/conda-forge/gdal-feedstock/issues/219#issuecomment-410577468

Note that even those are not guarantee to work due to a change in the behavior on how conda deals with features. (Ping @kalefranz and @msarahan for awareness.)
