### ISSUE TITLE
can't install geopandas with gdal=2.4.1 on python3.6 linux64

### ISSUE THREAD

**Issue by akrherz** [conda-forge/geopandas-feedstock#55]
Issue: I can't install geopandas with gdal=2.4.1 on linux64 for python 3.6.

```
$ conda create -n gdal python=3.6  gdal=2.4.1 geopandas
Collecting package metadata: done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - gdal=2.4.1
  - geopandas
Use "conda search <package> --info" to see the dependencies for each package.

$ cat ~/.condarc 
channel_priority: strict
channels:
  - conda-forge
  - defaults
```

My current "production" env is having trouble getting re-created and/or upgraded and not hit apparently broken gdal=2.4.0 builds in conda-forge.  I am trying to resolve why there is a logjam that is not permitting me to use gdal=2.4.1, which appears to work.  Thanks as always.

**Comment by ocefpaf** [comment]
Argh :-(

Looking into this... Hold on!

**Comment by akrherz** [comment]
Wow @ocefpaf , your support and effort is amazing.  thank you so much.

**Comment by ocefpaf** [comment]
If you unpin gdal or use `conda create -n gdal python=3.6 gdal=2.4.0 geopandas` it should work now. Basically I got the gdal 2.4.0 with the old openssl back. As soon as we fix https://github.com/conda-forge/qt-feedstock/pull/98 this issue will go away in "the right way" and you will be able to install `gdal=2.4.1`. Sorry about that. Qt is the hardest package we have in our stack and it is taking too long to build it. Unfortunately it blocks `matplotlib` and ends up affecting a lot of other packages b/c of that.

**Comment by akrherz** [comment]
Thank you, I was able to update my full env again and have a working GDAL 2.4.0
